//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value1.
        /// </summary>
        internal static string Key1 {
            get {
                return ResourceManager.GetString("Key1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value10.
        /// </summary>
        internal static string Key10 {
            get {
                return ResourceManager.GetString("Key10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value11.
        /// </summary>
        internal static string Key11 {
            get {
                return ResourceManager.GetString("Key11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value12.
        /// </summary>
        internal static string Key12 {
            get {
                return ResourceManager.GetString("Key12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value2.
        /// </summary>
        internal static string Key2 {
            get {
                return ResourceManager.GetString("Key2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value3.
        /// </summary>
        internal static string Key3 {
            get {
                return ResourceManager.GetString("Key3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value4.
        /// </summary>
        internal static string Key4 {
            get {
                return ResourceManager.GetString("Key4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value5.
        /// </summary>
        internal static string Key5 {
            get {
                return ResourceManager.GetString("Key5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value6.
        /// </summary>
        internal static string Key6 {
            get {
                return ResourceManager.GetString("Key6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value7.
        /// </summary>
        internal static string Key7 {
            get {
                return ResourceManager.GetString("Key7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value8.
        /// </summary>
        internal static string Key8 {
            get {
                return ResourceManager.GetString("Key8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value9.
        /// </summary>
        internal static string Key9 {
            get {
                return ResourceManager.GetString("Key9", resourceCulture);
            }
        }
    }
}
